### ISSUE TITLE
ASUS RT-AX92U - sed: /jffs/scripts/services-start: No such file or directory

### ISSUE THREAD

**Issue by pad0815** [Caleb9/asuswrt-merlin-nordvpn-wg-updater#4]
Hi,

after i run the sh install.sh i get the following message:

```
sh install.sh
Asuswrt-Merlin version: 388.8
JFFS partition: enabled
Router architecture: aarch64

Enabled WireGuard NordVPN clients:
[1] wgc3 (at120.nordvpn.com)
Select client instance for recommended server [1-1, e: exit]: 1
Downloading jq-linux-arm64 into /tmp/opt/usr/bin
Downloading nordvpn-updater.sh to /jffs/scripts
Schedule setting wgc3 to recommended server every two-hours? [Y/n, c: custom-schedule]: Y
sed: /jffs/scripts/services-start: No such file or directory
```

**Comment by Caleb9** [comment]
Hi @pad0815

Can you check if the `/jffs/scripts` directory exists, maybe also list its contents?

**Comment by pad0815** [comment]
Hi, yes, there is a file named "nordvpn-updater.sh"  

`User@RT-AX92U-FB50:/tmp/home/root# ls /jffs/scripts/
nordvpn-updater.sh`

In the content of the file there is a note of the requirement of jp ... is this the problem? And when, which version i need?

Thanks for your help!

**Comment by Caleb9** [comment]
No, the problem is that a file named `/jffs/scripts/services-start` doesn't exist, which is a bit weird. For example in my case the `/jffs/scripts` directory contains the following files:

```
ddns-start           nordvpn-updater.sh   service-event        services-stop
dnsmasq.postconf     post-mount           services-start       update-notification
```

You could maybe try to disable and enable again the "Administration -> System -> Enable JFFS custom scripts and configs" in the router's web UI, and see if the file gets created? Remember to click "Apply" after you disable it and then again when you enable it.

If that doesn't work, and the file is still missing, you can also try to create it manually:

```
echo "#!/bin/bash" > /jffs/scripts/services-start
chmod 755 /jffs/scripts/services-start
```
and retry the install script, but I'm not 100% certain if this will work if something else is different / missing in the system :S.

Let me know how it goes :).

**Comment by pad0815** [comment]
Okay, the required files do not appear, so i generate it as you describe an the installation was working! :)

`User@RT-AX92U-FB50:/tmp/home/root# echo "#!/bin/bash" > /jffs/scripts/services-start
User@RT-AX92U-FB50:/tmp/home/root# ls /jffs/scripts/
nordvpn-updater.sh  services-start
User@RT-AX92U-FB50:/tmp/home/root# chmod 755 /jffs/scripts/services-start
User@RT-AX92U-FB50:/tmp/home/root# sh install.sh
Asuswrt-Merlin version: 388.8
JFFS partition: enabled
Router architecture: aarch64

Enabled WireGuard NordVPN clients:
[1] wgc3 (at120.nordvpn.com)
Select client instance for recommended server [1-1, e: exit]: 1
'jq' already installed in /tmp/opt/usr/bin
Downloading nordvpn-updater.sh to /jffs/scripts
Schedule setting wgc3 to recommended server every two-hours? [Y/n, c: custom-schedule]: Y
Adding schedule to crontab
Saving schedule in /jffs/scripts/services-start
Last execution output log file: /var/log/nordvpn-updater-wgc3.log
Do you wish to run nordvpn-updater.sh now? [Y/n]: Y    
Thu Nov 14 20:36:06 CET 2024: setting wgc3 to at86

Installation completed
User@RT-AX92U-FB50:/tmp/home/root#`

Great!!! Thank you very much! 

I will test the reconnect in the next time, but it looks good :+1:
